version: "3"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: bl
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  # server:
  #   env_file: "./server/.env"
  #   build:
  #     context: ./server
  #     dockerfile: ./Dockerfile
  #   image: "server"
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db
